### ISSUE TITLE
Auto detecting threads

### ISSUE THREAD

**Issue by 3deep5me** [chenhunghan/ialacol#67]
Hi @chenhunghan,

nice project works good so far thanks for making this public available!

But i think the auto detecting threads feature does not work correctly, if i do not give the environment variable it runs on 8 threads although i have for example 16. After setting the env variable to 16 all threads are utilized.

Also one question, if i send requests in parallel is it normal that ialacol exits?

**Comment by chenhunghan** [comment]
Hello, by default the app will try to use half of you cpu core counts, for example if you have 16 cores and 32 threads, the `THREAD` will be set to 16. This was by designed because of past [experience](https://www.reddit.com/r/LocalLLaMA/comments/14djns5/llamacpp_and_thread_count_optimization/), however highly recommend to set it explicitly like you need, more threads does not necessary faster inference, you will need to find a balance for you hardware.

And for your second question, yes, because all your cores are busy and memory is likely full, it's recommend to put a queue in front of `ialacol`, for example https://github.com/ialacol/text-inference-batcher so it can process requests one by  one.

**Comment by 3deep5me** [comment]
Thank you for your fast reply!
